Update to version 1.03
* - When changing the theme URI one should not forget the footer.
* - Fixed: "Uncaught TypeError: $container.isotope is not a function".